#pragma once

#define WINDOW_W 960
#define WINDOW_H 800
#define WINDOW_N "Procedural Generation Constraint Satisfaction"

#define EXPAND 3

#define PIXEL_SCALE 4
#define CHUNK_WIDTH (WINDOW_W / PIXEL_SCALE)
#define CHUNK_HEIGHT (WINDOW_H / PIXEL_SCALE)
#define NUM_CHUNKS_WIDTH 1
#define NUM_CHUNKS_HEIGHT 1

#define SAMPLE_PIXEL_SCALE 16
#define SAMPLE_WIDTH (WINDOW_W / SAMPLE_PIXEL_SCALE)
#define SAMPLE_HEIGHT (WINDOW_H / SAMPLE_PIXEL_SCALE)

#define NUM_GENERATES_PER_ITERATION 20